version: "3"
services:
  customers_database:
    image: "mariadb:10.6.0"
    container_name: "customers_database"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_customerspwd
      - MYSQL_DATABASE=customers_database
      - MYSQL_USER=customersuser
      - MYSQL_PASSWORD=customerspwd
  artists_database:
    image: "mysql:8.0.25"
    container_name: "artists_database"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_artistspwd
      - MYSQL_DATABASE=artists_database
      - MYSQL_USER=artistsuser
      - MYSQL_PASSWORD=artistspwd
  items_database:
    image: "postgres:13.2"
    container_name: "items_database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=items_database
      - POSTGRES_USER=itemsuser
      - POSTGRES_PASSWORD=itemspwd
